version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onfly_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - onfly
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: onfly_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - onfly

  db:
    image: mysql:8.0
    container_name: onfly_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onfly
      MYSQL_USER: onfly
      MYSQL_PASSWORD: onfly
    ports:
      - "3323:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - onfly

networks:
  onfly:

volumes:
  db_data:
